---
kind: pipeline
name: e2e-pr-volatile

trigger:
  event:
  - pull_request
steps:
- name: test-e2e-volatile
  image: cypress/base:8
  environment:
    VUE_APP_BACKEND_TYPE: 'testVolatile'
  commands:
  - cd app
  - npm ci
  - npm run build
  - npm run test:e2e:run

---
kind: pipeline
name: e2e-pr-firebase

trigger:
  event:
  - pull_request
steps:
- name: deploy firebase rules
  image: node:lts-slim
  environment:
    FIREBASE_PROJECT:
      from_secret: FIREBASE_E2E_PROJECT
    FIREBASE_TOKEN:
      from_secret: FIREBASE_E2E_TOKEN
  commands:
  - cd app
  - npm i -g firebase-tools
  - firebase deploy --only firestore:rules --token "$FIREBASE_TOKEN" --project $FIREBASE_PROJECT
- name: test-e2e-firebase
  image: cypress/base:8
  environment:
    VUE_APP_BACKEND_TYPE: 'firebase'
    VUE_APP_BACKEND_PROJECT:
      from_secret: FIREBASE_E2E_PROJECT
    VUE_APP_BACKEND_KEY:
      from_secret: FIREBASE_E2E_CLIENTKEY
    FIREBASE_SERVICEACCOUNT:
      from_secret: FIREBASE_E2E_ACCOUNTKEY
  commands:
  - cd app
  - npm ci
  - node cypress/wipe-firestore.js
  - npm run build
  - npm run test:e2e:run
