---
kind: pipeline
name: editor

steps:
- name: lint
  image: node:lts-slim
  commands:
  - cd editor
  - npm ci
  - npm run lint
- name: build
  image: node:lts-slim
  commands:
  - cd editor
  - npm ci
  - npm run build
- name: netlify deploy
  image: node:lts-alpine
  environment:
    NETLIFY_SITE_ID:
      from_secret: NETLIFY_EDITOR_ID
    NETLIFY_AUTH_TOKEN:
      from_secret: NETLIFY_TOKEN
  commands:
    - cd editor
    - npm install -g netlify-cli
    - netlify deploy --dir=dist --prod
  when:
    branch:
    - master
- name: docker publish editor
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: anoff/devradar
    target: editor
    tags: latest
    dockerfile: editor/Dockerfile
  when:
    branch:
    - master
- name: radar.anoff.io
  image: node:lts-slim
  environment:
    FIREBASE_PROJECT:
      from_secret: FIREBASE_PROJECT
    FIREBASE_TOKEN:
      from_secret: FIREBASE_TOKEN
  commands:
  - cd editor
  - npm ci
  - cp -R anoff/** .
  - npm run build
  - npm i -g firebase-tools
  - firebase deploy --token "$FIREBASE_TOKEN" --project $FIREBASE_PROJECT
  when:
    branch:
    - master


---
kind: pipeline
name: teams

steps:
- name: lint
  image: node:lts-slim
  commands:
  - cd teams
  - npm ci
  - npm run lint
- name: build
  image: node:lts-slim
  commands:
  - cd teams
  - npm ci
  - npm run build
- name: netlify deploy
  image: node:lts-alpine
  environment:
    NETLIFY_SITE_ID:
      from_secret: NETLIFY_TEAMS_ID
    NETLIFY_AUTH_TOKEN:
      from_secret: NETLIFY_TOKEN
  commands:
    - cd teams
    - npm install -g netlify-cli
    - netlify deploy --dir=dist --prod
  when:
    branch:
    - master