[meta]
title = "Tammy's devradar"
categories = [ "Tools", "Techniques", "Platforms", "Frameworks" ]
levels = [ "Novice", "Intermediate", "Advanced", "Veteran" ]

[[blips]]
category = 3
title = "Javascript"
level = 2

  [[blips.changes]]
  date = "2019-06"
  newLevel = 2

[[blips]]
category = 3
title = "CSS"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3

[[blips]]
category = 1
title = "Design"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3

[[blips]]
category = 2
title = "GitHub"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3

[[blips]]
category = 0.0
title = "Circle CI"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3

[[blips]]
category = 0.0
title = "Drone CI"
level = 1

  [[blips.changes]]
  date = "2019-06"
  newLevel = 1

[[blips]]
category = 0.0
title = "Netlify"
level = 2

  [[blips.changes]]
  date = "2019-06"
  newLevel = 2

[[blips]]
category = 2
title = "zeit.now"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3

[[blips]]
category = 1
title = "Web Development"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3

[[blips]]
category = 3
title = "HTML"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3

[[blips]]
category = 3
title = "Material Design"
level = 2

  [[blips.changes]]
  date = "2019-06"
  newLevel = 2

[[blips]]
category = 3
title = "Angular"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3

[[blips]]
category = 3
title = "React"
level = 1

  [[blips.changes]]
  date = "2019-06"
  newLevel = 1

[[blips]]
category = 3
title = "Vue.js"
level = 0.0

  [[blips.changes]]
  date = "2019-06"
  newLevel = 0.0

[[blips]]
category = 2
title = "Heroku"
level = 2

  [[blips.changes]]
  date = "2019-06"
  newLevel = 2
