[meta]
title = "Galactic Federation Technology Stack"
categories = [ "Tools", "Techniques", "Platforms", "Frameworks" ]
levels = [ "Hold", "Assess", "Trial", "Adopt" ]

[[blips]]
category = 0
title = "GitLab CI"
level = 3

  [[blips.changes]]
  date = "2018-07"
  newLevel = 3

[[blips]]
category = 3
link = "https:////nodejs.org"
description = "Javascript in the backend? 🤯"
title = "Node.js"
level = 3

  [[blips.changes]]
  date = "2018-07"
  newLevel = 3
  text = "made it into the common toolstack"

  [[blips.changes]]
  date = "2014-12"
  newLevel = 2
  text = "test it with this new backend"

[[blips]]
category = 2
link = "https:////kubernetes.io"
description = "Containers at scale"
title = "Kubernetes"
level = 3

  [[blips.changes]]
  date = "2018-07"
  newLevel = 3
  text = "de facto standard for all our container orchestration needs"

[[blips]]
category = 2
link = "https:////docker.io"
description = "Container all the things"
title = "Docker"
level = 3

  [[blips.changes]]
  date = "2019-03"
  newLevel = 3

[[blips]]
category = 1
description = "Treat your documentation like you treat code, git version, PR review, etc."
title = "docs as code"
level = 2

  [[blips.changes]]
  date = "2019-03"
  newLevel = 2
  text = "This seems like a good idea, we should do more of it"

[[blips]]
category = 3
description = "Scripting and stuff"
title = "Python"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3
  text = ""

[[blips]]
category = 1
title = "CI/CD"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3

[[blips]]
category = 0
title = "Azure DevOps"
level = 1

  [[blips.changes]]
  date = "2019-06"
  newLevel = 1

[[blips]]
category = 3
title = "Vue.js"
level = 2

  [[blips.changes]]
  date = "2019-06"
  newLevel = 2

[[blips]]
category = 3
title = "Angular"
level = 2

  [[blips.changes]]
  date = "2019-06"
  newLevel = 2

[[blips]]
category = 0
title = "Jenkins"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3

[[blips]]
category = 1
title = "Infrastructure as Code"
level = 2

  [[blips.changes]]
  date = "2019-06"
  newLevel = 2

[[blips]]
category = 0
title = "Terraform"
level = 2

  [[blips.changes]]
  date = "2019-06"
  newLevel = 2

[[blips]]
category = 0
title = "Ansible"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3

[[blips]]
category = 1
title = "Web Design"
level = 2

  [[blips.changes]]
  date = "2019-06"
  newLevel = 2

[[blips]]
category = 3
title = "C++"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3

[[blips]]
category = 2
title = "Azure IaaS"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3

[[blips]]
category = 2
title = "Azure P/SaaS"
level = 2

  [[blips.changes]]
  date = "2019-06"
  newLevel = 2

[[blips]]
category = 2
title = "GitHub"
level = 1

  [[blips.changes]]
  date = "2019-06"
  newLevel = 1

[[blips]]
category = 2
title = "BitBucket"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3
